name: Greetings from @MrKrishnaAgarwal

on: [issues, issue_comment, fork, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey, Welcome to this repo, Congratulations on opening your first issue. Keep Contributing"
        pr-message: "Hey, Welcome to this repo, Congratulations on opening your first Pull Requests. Keep Contributing"
        footer: 'I will try to review your profile as soon as possible and will give you the best suggestions to improve it. Meanwhile, You can also Follow me on <a href="https://github.com/MrKrishnaAgarwal">GitHub</a>, and <a href="https://twitter.com/DMKrishnaA">Twitter</a> also Feel free to checkout my other cool <a href="https://github.com/MrKrishnaAgarwal?tab=repositories">repositories</a> and <a href="https://dev.to/krishnaagarwal">articles</a>'
