on:
  fork:
  push:
    branches: [develop]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>Hey, Welcome to this repo, Congratulations on opening your first issue. Keep Contributing</h1>'
          pr-message: '<h1>Hey, Welcome to this repo, Congratulations on opening your first Pull Requests. Keep Contributing</h1>'
          footer: 'I will try to review your profile as soon as possible and will give you the best suggestions to improve it. Meanwhile, You can also Follow me on <a href="https://github.com/MrKrishnaAgarwal">GitHub</a>, and <a href="https://twitter.com/DMKrishnaA">Twitter</a> also Feel free to checkout my other cool <a href="https://github.com/MrKrishnaAgarwal?tab=repositories">repositories</a> and <a href="https://dev.to/krishnaagarwal">articles</a>'
